=== Scooby2112/CBS_ITVDN/src/main/resources/Beer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="Chars">
        <xs:sequence>
            <xs:element name="ABV" type="xs:string"/>
            <xs:element name="Transparency" type="xs:string"/>
            <xs:element name="Filtered" type="xs:boolean"/>
            <xs:element name="Calories" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Ingredients">
        <xs:sequence>
            <xs:element name="Ingredient" minOccurs="0" maxOccurs="unbounded">
                <xs:simpleType>
                    <xs:restriction base="xs:string" >
                        <xs:enumeration value="Water"/>
                        <xs:enumeration value="Malt"/>
                        <xs:enumeration value="Hops"/>
                        <xs:enumeration value="Pectin"/>
                        <xs:enumeration value="Coriander"/>
                        <xs:enumeration value="Yeast"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Beer">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Type" type="xs:string"/>
            <xs:element name="Alcohol" type="xs:boolean"/>
            <xs:element name="Ingredients" type="Ingredients"/>
            <xs:element name="Chars" type="Chars"/>
        </xs:sequence>
        <xs:attribute name="Manufacturer" type="xs:string"/>
    </xs:complexType>

    <xs:element name="Beers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Beer" type="Beer" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== Scooby2112/CBS_ITVDN/src/main/resources/Beer.xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Beers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Beer.xsd">

  <Beer Manufacturer="Example Brewery">
    <Name>Example Beer</Name>
    <Type>Light</Type>
    <Alcohol>Yes</Alcohol>
    <Ingredients>
      <Ingredient>Water</Ingredient>
      <Ingredient>Malt</Ingredient>
      <Ingredient>Hops</Ingredient>
    </Ingredients>
    <Chars>
      <ABV>5%</ABV>
      <Transparency>90%</Transparency>
      <Filtered>Yes</Filtered>
      <Calories>150 kcal</Calories>
    </Chars>
  </Beer>
</Beers>

=== Scooby2112/CBS_ITVDN/src/main/resources/beers-transformed.xml
<?xml version="1.0" encoding="UTF-8"?>
<Beers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="Beer.xsd">

    <Beer Manufacturer="Example Brewery">
        <Name>Example Beer</Name>
        <Type>Light</Type>
        <Alcohol>true</Alcohol>
        <Ingredients>
            <Ingredient>Water</Ingredient>
            <Ingredient>Malt</Ingredient>
            <Ingredient>Hops</Ingredient>
            <Ingredient>Yeast</Ingredient>
            <Ingredient>Coriander</Ingredient>
        </Ingredients>
        <Chars>
            <ABV>5%</ABV>
            <Transparency>90%</Transparency>
            <Filtered>true</Filtered>
            <Calories>150 kcal</Calories>
        </Chars>
    </Beer>

    <Beer Manufacturer="Уманьпиво">
        <Name>Waissburg</Name>
        <Type>Light</Type>
        <Alcohol>true</Alcohol>
        <Ingredients>
            <Ingredient>Water</Ingredient>
            <Ingredient>Malt</Ingredient>
            <Ingredient>Hops</Ingredient>
            <Ingredient>Pectin</Ingredient>
            <Ingredient>Coriander</Ingredient>
            <Ingredient>Yeast</Ingredient>
        </Ingredients>
        <Chars>
            <ABV>4.7%</ABV>
            <Transparency>80%</Transparency>
            <Filtered>true</Filtered>
            <Calories>175 kcal</Calories>
        </Chars>
    </Beer>

</Beers>
